import type { Metadata } from "next";
import "./globals.css";
import styles from "@/app/styles/Home.module.css";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={styles.main}>
          <div>{children}</div>
        </body>
      </html>
    </ClerkProvider>
  );
}
